package cours.hibernate.entities;
// Generated 19 oct. 2017 12:11:18 by Hibernate Tools 4.3.1



/**
 * Ligcdes generated by hbm2java
 */
public class Ligcdes  implements java.io.Serializable {


     private LigcdesId id;
     private Cdes cdes;
     private Produits produits;
     private int qte;

    public Ligcdes() {
    }

    public Ligcdes(LigcdesId id, Cdes cdes, Produits produits, int qte) {
       this.id = id;
       this.cdes = cdes;
       this.produits = produits;
       this.qte = qte;
    }
   
    public LigcdesId getId() {
        return this.id;
    }
    
    public void setId(LigcdesId id) {
        this.id = id;
    }
    public Cdes getCdes() {
        return this.cdes;
    }
    
    public void setCdes(Cdes cdes) {
        this.cdes = cdes;
    }
    public Produits getProduits() {
        return this.produits;
    }
    
    public void setProduits(Produits produits) {
        this.produits = produits;
    }
    public int getQte() {
        return this.qte;
    }
    
    public void setQte(int qte) {
        this.qte = qte;
    }




}


