package cours.hibernate.entities;
// Generated 19 oct. 2017 12:11:18 by Hibernate Tools 4.3.1



/**
 * LigcdesId generated by hbm2java
 */
public class LigcdesId  implements java.io.Serializable {


     private int idCde;
     private int idProduit;

    public LigcdesId() {
    }

    public LigcdesId(int idCde, int idProduit) {
       this.idCde = idCde;
       this.idProduit = idProduit;
    }
   
    public int getIdCde() {
        return this.idCde;
    }
    
    public void setIdCde(int idCde) {
        this.idCde = idCde;
    }
    public int getIdProduit() {
        return this.idProduit;
    }
    
    public void setIdProduit(int idProduit) {
        this.idProduit = idProduit;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LigcdesId) ) return false;
		 LigcdesId castOther = ( LigcdesId ) other; 
         
		 return (this.getIdCde()==castOther.getIdCde())
 && (this.getIdProduit()==castOther.getIdProduit());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCde();
         result = 37 * result + this.getIdProduit();
         return result;
   }   


}


