package cours.hibernate.entities;
// Generated 19 oct. 2017 12:11:18 by Hibernate Tools 4.3.1



/**
 * Utilisateurs generated by hbm2java
 */
public class Utilisateurs  implements java.io.Serializable {


     private String pseudo;
     private String mdp;
     private String email;
     private String qualite;

    public Utilisateurs() {
    }

    public Utilisateurs(String pseudo, String mdp, String email, String qualite) {
       this.pseudo = pseudo;
       this.mdp = mdp;
       this.email = email;
       this.qualite = qualite;
    }
   
    public String getPseudo() {
        return this.pseudo;
    }
    
    public void setPseudo(String pseudo) {
        this.pseudo = pseudo;
    }
    public String getMdp() {
        return this.mdp;
    }
    
    public void setMdp(String mdp) {
        this.mdp = mdp;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getQualite() {
        return this.qualite;
    }
    
    public void setQualite(String qualite) {
        this.qualite = qualite;
    }




}


