package cours.hibernate.entities;
// Generated 19 oct. 2017 12:11:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vendeurs generated by hbm2java
 */
public class Vendeurs  implements java.io.Serializable {


     private Integer idVendeur;
     private Vendeurs vendeurs;
     private Villes villes;
     private String nom;
     private Set<VendeursVilles> vendeursVilleses = new HashSet<VendeursVilles>(0);
     private Set<Ventes> venteses = new HashSet<Ventes>(0);
     private Set<Vendeurs> vendeurses = new HashSet<Vendeurs>(0);

    public Vendeurs() {
    }

	
    public Vendeurs(Vendeurs vendeurs, Villes villes, String nom) {
        this.vendeurs = vendeurs;
        this.villes = villes;
        this.nom = nom;
    }
    public Vendeurs(Vendeurs vendeurs, Villes villes, String nom, Set<VendeursVilles> vendeursVilleses, Set<Ventes> venteses, Set<Vendeurs> vendeurses) {
       this.vendeurs = vendeurs;
       this.villes = villes;
       this.nom = nom;
       this.vendeursVilleses = vendeursVilleses;
       this.venteses = venteses;
       this.vendeurses = vendeurses;
    }
   
    public Integer getIdVendeur() {
        return this.idVendeur;
    }
    
    public void setIdVendeur(Integer idVendeur) {
        this.idVendeur = idVendeur;
    }
    public Vendeurs getVendeurs() {
        return this.vendeurs;
    }
    
    public void setVendeurs(Vendeurs vendeurs) {
        this.vendeurs = vendeurs;
    }
    public Villes getVilles() {
        return this.villes;
    }
    
    public void setVilles(Villes villes) {
        this.villes = villes;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set<VendeursVilles> getVendeursVilleses() {
        return this.vendeursVilleses;
    }
    
    public void setVendeursVilleses(Set<VendeursVilles> vendeursVilleses) {
        this.vendeursVilleses = vendeursVilleses;
    }
    public Set<Ventes> getVenteses() {
        return this.venteses;
    }
    
    public void setVenteses(Set<Ventes> venteses) {
        this.venteses = venteses;
    }
    public Set<Vendeurs> getVendeurses() {
        return this.vendeurses;
    }
    
    public void setVendeurses(Set<Vendeurs> vendeurses) {
        this.vendeurses = vendeurses;
    }




}


