package cours.hibernate.entities;
// Generated 19 oct. 2017 12:11:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Villes generated by hbm2java
 */
public class Villes  implements java.io.Serializable {


     private String cp;
     private Pays pays;
     private String nomVille;
     private String site;
     private String photo;
     private Set<Vendeurs> vendeurses = new HashSet<Vendeurs>(0);
     private Set<VendeursVilles> vendeursVilleses = new HashSet<VendeursVilles>(0);
     private Set<Clients> clientses = new HashSet<Clients>(0);

    public Villes() {
    }

	
    public Villes(String cp, Pays pays, String nomVille) {
        this.cp = cp;
        this.pays = pays;
        this.nomVille = nomVille;
    }
    public Villes(String cp, Pays pays, String nomVille, String site, String photo, Set<Vendeurs> vendeurses, Set<VendeursVilles> vendeursVilleses, Set<Clients> clientses) {
       this.cp = cp;
       this.pays = pays;
       this.nomVille = nomVille;
       this.site = site;
       this.photo = photo;
       this.vendeurses = vendeurses;
       this.vendeursVilleses = vendeursVilleses;
       this.clientses = clientses;
    }
   
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }
    public Pays getPays() {
        return this.pays;
    }
    
    public void setPays(Pays pays) {
        this.pays = pays;
    }
    public String getNomVille() {
        return this.nomVille;
    }
    
    public void setNomVille(String nomVille) {
        this.nomVille = nomVille;
    }
    public String getSite() {
        return this.site;
    }
    
    public void setSite(String site) {
        this.site = site;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public Set<Vendeurs> getVendeurses() {
        return this.vendeurses;
    }
    
    public void setVendeurses(Set<Vendeurs> vendeurses) {
        this.vendeurses = vendeurses;
    }
    public Set<VendeursVilles> getVendeursVilleses() {
        return this.vendeursVilleses;
    }
    
    public void setVendeursVilleses(Set<VendeursVilles> vendeursVilleses) {
        this.vendeursVilleses = vendeursVilleses;
    }
    public Set<Clients> getClientses() {
        return this.clientses;
    }
    
    public void setClientses(Set<Clients> clientses) {
        this.clientses = clientses;
    }




}


